title: "Shirel's Hub"
logo: "/files/shirelmr.png?raw=true" # your photo (or logo) here
description: >
 Bio: <br>
 Shirel Marino Ramirez <br>
  ğŸ‘©ğŸ»â€ğŸ’» Software Engineer <br>
 ğŸ“ Puebla, Mexico <br>
 ğŸ“ GPA: 96/100 <br>
  ğŸ“… Graduation date (expected): June 2027 <br><br>

 Code with purpose
 

theme: jekyll-theme-minimal
