title: "Shirel's Hub"
logo: "/files/shirelmr.png?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hi! I am Shirel Marino, and I'm from Puebla. I'm a dedicated second-year Computer Science student at  <a href= "https://tec.mx/es/computacion-y-tecnologias-de-informacion/ingenieria-en-tecnologias-computacionales"> Tecnol√≥gico de Monterrey  </a> with passion for technology and its ability to adress real-world challenges. I have worked with C++ programming, app developent and web development but also I'm interested in transformative fields like Artificial Intelligence (AI) and cybersecurity, which inspire me to innovate and contribute to impactful solutions.
 <br>
 

theme: jekyll-theme-minimal
