title: Shirel's Homepage # your name (or website title) here
logo: "/files/shirelmr.png?raw=true" # your photo (or logo) here
description: >
 Abstract: <br>
 Hi! I am Shirel Marino a third semester Computer Science student ğŸ’» with an interest in artificial intelligence ğŸ¤–,
 machine learning, cybersecurity ğŸ”, and software development. I have worked on projects that combine programming 
 and technology, I am passionate about applying this knowledge to solve practical problems.
 <br>
 

theme: jekyll-theme-minimal
