title: "Shirel's Hub"
logo: "/files/shirelmr.png?raw=true" # your photo (or logo) here
description: >
 Bio: <br><br>
 Shirel Marino Ramirez <br><br>
  ğŸ‘©ğŸ»â€ğŸ’» Software Engineer <br>
 ğŸ“ Puebla, Mexico <br>
 ğŸ“ GPA: 96/100 <br>
  ğŸ“… Graduation date (expected): June '27 <br><br>

 Code with purpose <br><br>
 

theme: jekyll-theme-minimal
